### ISSUE TITLE
kubectl get cs UnHealthy

### ISSUE THREAD

**Issue by qiangwum** [qiangwum/blogs#5]
scheduler Unhealthy Get “http://127.0.0.1:10251/healthz“: dial tcp 127.0.0.1:10251: con

**Comment by qiangwum** [comment]
> https://blog.csdn.net/qq_34556414/article/details/121940591?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_title~default-0.queryctrv4&spm=1001.2101.3001.4242.1&utm_relevant_index=2

**Comment by qiangwum** [comment]
解决方法：
cd /etc/kubernetes/manifest
然后将你的scheduler以及controll manager .yaml中都port=0注释掉
```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
      #    - --port=0
    image: registry.aliyuncs.com/google_containers/kube-scheduler:v1.22.7
    imagePullPolicy: IfNotPresent
```
